Fix bug in title/url blocking regex (#969)
Fix the exception `AttributeError: 'Filter' object has no attribute 'block_url'`
introduced in this commit [1].

`self.block_title` and `self.block_url` were members of the Filter
object[2], but not anymore after commit [1].

This bug can be reproduced with setting WHOOGLE_CONFIG_BLOCK_URL to a
non-empty string.

[1] https://github.com/benbusby/whoogle-search/commit/10a15e06e1bf6f1a22d1625950d8c221d99d6a07
[2] https://github.com/benbusby/whoogle-search/commit/284a8102c85bdc69674952bc30a6cfacfb8b01ee